language: ruby
cache: bundler

rvm:
  - ruby-head
  - 2.6.0
  - 2.5.3
  - 2.4.5
  - 2.3.8

branches:
  only:
    - master
    - development

before_install:
  - gem install bundler
  - gem install rubocop

before_script: rubocop --fail-level=W
