language: ruby
cache: bundler

rvm:
  - ruby-head
  - 2.6.1
  - 2.5.3
  - 2.4.5
  - 2.3.8

branches:
  only:
    - master
    - development

before_install:
  - travis_retry gem update --system || travis_retry gem update --system 2.7.8
  - travis_retry gem install bundler --no-document || travis_retry gem install bundler --no-document -v 1.17.3
  - travis_retry gem install rubocop --no-document

before_script: rubocop --fail-level=W
